# ls
alias l='ls -Glh'
alias la='ls -Ga'
alias ls='ls -G'
alias ll='ls -Glhsa'

# general
alias ..='cd ..'
alias c='clear'
alias h='history'
alias j='jobs'
alias m='man'
alias mkdir='mkdir -p'
alias mount='mount | column -t'
alias sha1='openssl sha1'
alias wan='curl ifconfig.me'
alias wget='wget -c'

# git aliases
alias g='git'
alias ga='git a'
alias gbr='git br'
alias gci='git ci'
alias gcl='git cl'
alias gco='git co'
alias gcp='git cp' 
alias gd='git d'
alias gdlc='git dlc'
alias ggr='git gr'
alias gi='git i'
alias gld='git ld'
alias gle='git le'
alias gll='git ll'
alias gls='git ls'
alias gs='git s'

# processes 
alias psaux='ps aux | grep'

# safety
alias cp='cp -i'
alias mv='mv -i'

# sudo 
alias root='sudo -i'
alias s='sudo'
alias su='sudo -i'

# tar
alias taru='tar -xf'
alias tarc='tar -cf'

alias lldb='sudo lldb'
alias gdb='sudo lldb'
